name: 'Befoxi Studios'
icon: 'https://dummyimage.com/64x64/404040/404040.png'
table:
  - name: 'Plan Name'
    baseColor: '#ff2160'
    list:
      - name: "Works Content"
  - name: 'Second table'
    baseColor: '#904bd1'
    list:
      - name: "Same first"
        tags: ["tag", "custom", "yourself"]
      - name: "Secend list"
